/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guideSidebar: [
    `tribes-guides-index`,
    `guide-install-setup`,
    `guide-config`,
    {
      type: 'category', 
      label: 'Gameplay Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'gameplay',
        },
      ],
    },
    {
      type: 'category', 
      label: 'Development Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
    {
      type: 'category', 
      label: 'Custom Maps',
      items: [
        {
          type: 'autogenerated',
          dirName: 'custommaps', 
        },
      ],
    },
    {
      type: 'category', 
      label: 'Tribes Information',
      items: [
        {
          type: 'autogenerated',
          dirName: 'information',
        },
      ],
    },
    {
      type: 'category', 
      label: 'Tribes Servers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'servers',
        },
      ],
    },
    {
      type: 'category', 
      label: 'Tribes Speedrunning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'speedrunning',
        },
      ],
    },
  ],
  otherSide:[
    {
      type: 'autogenerated',
      dirName: 'not-tribes', 
    },
  ]
};

module.exports = sidebars;
