import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { NavBar } from "./_components/navbar";
import { Footer } from "./_components/Footer";

import { TRPCReactProvider } from "~/trpc/react";

import { ClerkProvider } from "@clerk/nextjs";

import { MantineProvider } from "@mantine/core";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <MantineProvider>
            <NavBar />
            <TRPCReactProvider cookies={cookies().toString()}>
              <main className="flex h-fit min-h-screen w-full flex-col items-center gap-6 py-6">
                {children}
              </main>
            </TRPCReactProvider>
            <Footer />
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
